-- =====================================================================
-- MySQL database for the escape room game: two tables, Users and Hints.
-- Run with:  mysql -u root -p < database.sql
-- =====================================================================

USE game_database;

-- ---------------------------------------------------------------------
-- Users
-- user_id is the PRIMARY KEY and is generated by MySQL (AUTO_INCREMENT).
-- password stores a hash produced by the application, never plain text.
-- There is no email column.
-- ---------------------------------------------------------------------
CREATE TABLE Users (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    room_id INT,
    connection_status VARCHAR(20) DEFAULT 'Disconnected',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------------
-- Hints
-- hint_id is the PRIMARY KEY and is generated by MySQL (AUTO_INCREMENT).
-- user_id is a FOREIGN KEY -> Users.user_id (one user, many hints).
-- ---------------------------------------------------------------------
CREATE TABLE Hints (
    hint_id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    room_id INT,
    hint_text TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (user_id)
        REFERENCES Users(user_id)
);

-- ---------------------------------------------------------------------
-- Sample records (IDs are generated automatically: 1, 2, 3, 4, 5)
-- ---------------------------------------------------------------------
INSERT INTO Users
(username, password, room_id, connection_status)
VALUES
('Ahmed', 'hashed_password_1', 1, 'Connected'),
('Omar', 'hashed_password_2', 1, 'Connected'),
('Ali', 'hashed_password_3', 1, 'Disconnected'),
('Hassan', 'hashed_password_4', 2, 'Connected'),
('Khalid', 'hashed_password_5', 2, 'Connected');

INSERT INTO Hints
(user_id, room_id, hint_text)
VALUES
(1, 1, 'Check the room near the entrance.'),
(2, 1, 'Look behind the first object.'),
(1, 1, 'The answer contains a number.'),
(3, 1, 'Check the second clue.'),
(2, 1, 'Look underneath the object.');

-- ---------------------------------------------------------------------
-- Verification
-- ---------------------------------------------------------------------
SHOW TABLES;
DESCRIBE Users;
DESCRIBE Hints;

-- Shows Hints.user_id -> Users.user_id
SELECT TABLE_NAME, COLUMN_NAME, REFERENCED_TABLE_NAME, REFERENCED_COLUMN_NAME
FROM information_schema.KEY_COLUMN_USAGE
WHERE TABLE_SCHEMA = 'game_database' AND REFERENCED_TABLE_NAME IS NOT NULL;
